[project]
name = "mount-linker"
version = "0.1.0"
description = "Automatically link devices on mount to a more convenient location."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "watchdog>=6.0.0",
]
